#!/bin/sh
set -e

rm -f subs-playass.ass
ffmpeg -y -i "$1" -map 0:s -c:s copy subs-playass.ass
dos2unix subs-playass.ass
filename="$1.translated.ass"
if [ ! -e "$filename" ] ; then
	cat subs-playass.ass | translate-ass $2 | tee "$1.translated.ass"
fi
rm -f subs-playass.ass
ffplay "$1" -vf "ass=$filename"

